import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/utils/smoothScroll";

import { getSiteSettings } from "./queries/getSiteSettings";
import { generateMetadata as genMeta } from "./queries/generateMetaData";

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export async function generateMetaData() {
  const settings = await getSiteSettings();

  return genMeta({
    siteName: settings?.siteName,
    siteUrl: settings?.siteUrl,
    defaultSeo: settings?.defaultSeo,
  });
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceMono.variable}>
      <body className="antialiased">
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
